# Generated by Django 4.1.3 on 2022-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='notename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='notenames',
        ),
    ]
